name: Create issue on commit and access REST API 

on: [ push ]

jobs: 
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit ${{ github.sha }}",
            "body": "Automatically created by the Github Action workflow **${{ github.workflow }}**. \n\n The commit hash was _${{ github.sha }}_."
          }' \
          --fail