name: Set Environment Variables examples

on: [push]

jobs:
  setup-and-use-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set dynamic environment variables
        run: |
          # Using workflow command to set an environment variable
          echo "DYNAMIC_VAR=Hello from Github Actions" >> $GITHUB_ENV
        
      - name: Use the environment variable
        run: |
          # Using the environment variable in a subsequent step
          echo "The value of DYNAMIC_VAR is: $DYNAMIC_VAR" 


