name: Caching primes
# Restoring and saving cache using a single action
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Cache primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Generate prime numbers 
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Use prime numbers
        run: ./primes.sh -d prime-numbers
