name: Greeting on a variable day 

on: workflow_dispatch

env:
  # Workflow level env var
  DAY_OF_THE_WEEK: 'Monday'

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_THE_WEEK"
        env:
          First_Name: Mona 
